### ISSUE TITLE
Workflow Smart button import fails

### ISSUE THREAD

**Issue by NixonFin** [scottdurow/RibbonWorkbench#13] opened 2017-03-29 07:14 UTC
Hi, 

I'm running D365 8.2, Ribbon workbench 3.1.2 and tried to add Workflow smart button, with following steps:
- Dragged the button on ribbon, added Title and workflow name and tried to import solution

 Solution import fails with following error.

![image](https://cloud.githubusercontent.com/assets/26760796/24442715/0adb5c44-1468-11e7-8c2b-abddbd7494f4.png)

Ps. This same error can be produced also on Ribbon workbench 3.0.25

**Comment by arjen-lammers** [comment] 2017-04-18 13:18
Had the same problem, Solved by adding a value for callback javascript and confirmation message. If you look at the xml it is quite clear what the problem is.
\<Actions>
        \<JavaScriptFunction FunctionName="SmartButtons.ClientHooks.SmartButtons.RunWorkflowMultiple" Library="$webresource:dev1_/js/SmartButtons.ClientHooks.js">
          \<StringParameter Value="Workflow1" />
          \<CrmParameter Value="SelectedControlSelectedItemIds" />
          \<StringParameter **Value=""** />
          \<StringParameter **Value=""** />
        \</JavaScriptFunction>
      \</Actions>

**Comment by scottdurow** [comment] 2017-09-10 17:33
Fixed in 1.2.85.1

**Closed by scottdurow** 2017-09-10 17:33 UTC
Labels: bug
